blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name


urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name="Заголовок", help_text="Введите заголовок",)
    slug = models.CharField(max_length=50, verbose_name="Ссылка", help_text="Введите ссылку",)
    content = models.TextField(verbose_name="Содержимое", help_text="Введите содержимое", blank=True, null=True)
    photo = models.ImageField(upload_to="photo", blank=True, null=True, verbose_name="Изображение")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    views = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров",
                                        help_text="Укажите количество просмотров")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'is_published', 'photo')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'is_published', 'photo')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        from django.urls import reverse
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/home.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить блог "{{ object.title}}"?</p>
                        <button type="submit" class="btn btn-primary">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-primary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Блог: "{{ object.title }}" ({{ object.slug }})</h4>
                </div>
                <div class="col-12">
                    <img src="{{ object.photo | media_filter }}">
                </div>

                <div class="card-body">
                    <p>
                        Дата создания: {{ object.created_at }}
                    </p>
                    <p>
                        {{ object.content }}
                    </p>
                    <a class="btn btn-primary" href="{% url 'blog:list' %}" role="button">Вернуться к списку постов</a>
                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/home.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form class="row" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                                Изменить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}
<div class="col-3">
    <div class="mb-4 text-center">
        <div class="card-header">
            <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:create' %}" role="button">Создать блог</a>
        </div>
    </div>
</div>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 text-center">
    {% for blog in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Блог: {{ blog.title }}</h4>
            </div>
            <div class="card-body">
                <div class="col-12">
                    <img src="{{ blog.photo | media_filter }}">
                </div>
                <h6 class="card-title pricing-card-title">Содержимое: {{ blog.content|slice:25 }}...</h6>
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:view' blog.pk %}" role="button">Подробно</a>
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:edit' blog.pk %}" role="button">Изменить</a>
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:delete' blog.pk %}" role="button">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}